


/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {

};

// String t is generated by random shuffling
// Math.floor dot random on String s 
// add one more leetter at a randmo position
// RETURN the letter that was added to t


Question:
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 Ex 1)
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.