


/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {

};

// String t is generated by random shuffling
// Math.floor dot random on String s 
// add one more leetter at a randmo position
// RETURN the letter that was added to t